baseURL: "/"
title: BlackStewie
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
enableEmoji: true
# Enable Disqus comments
# disqusShortname: yourdiscussshortname

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 4
    ordered: true
    startLevel: 2
  highlight:
    noClasses: false

params:
  author: Michael Schaecher
  license: "<a rel=license href=https://mit-license.org>MIT</a>"

  description: Michael Schaecher's personal website
  keywords: blog,developer,personal
  info: The nerdy tech stuff that I've forgotten.

  faviconSVG: icons/favicon.ico
  favicon_32: icons/favicon-32x32.png
  favicon_16: icons/favicon-16x16.png

  # Set an image to be used as part of the listing of blogs and posts.
  images:
    avatarURL: images/avatar.svg
    #gravatar: john.doe@example.com
    postlistIMG: /images/posts/backdrop.png

  # Use custom image for 404 page. Useful
  missingPage: images/404.svg

  dateFormat: January 2, 2006
  since: 2023

  # Right To Left, shift content direction for languagues such as Arabic
  rtl: false
  # Specify light/dark colorscheme
  # Supported values:
  # auto (use preference set by browser)
  # dark (dark background, light foreground)
  # light (light background, dark foreground) (default)
  colorScheme: dark
  # Hide the toggle button, along with the associated vertical divider
  hideColorSchemeToggle: true
  # Series see also post count
  maxSeeAlsoItems: 5
  # Custom CSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
  customSCSS:

  # Custom JS
  customJS:

  # Custom remote JS files
  customRemoteJS:

  # If you want to use fathom(https://usefathom.com) for analytics, add this section
  #fathomAnalytics:
  #  siteID: ABCDE
  #  serverURL: analytics.example.com # Default value is cdn.usefathom.com, overwrite this if you are self-hosting

  # If you want to use plausible(https://plausible.io) for analytics, add this section
  #plausibleAnalytics:
  #  domain: example.com
  #  serverURL: analytics.example.com # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
  #  outboundLinksTracking: true
  #  fileDownloadsTracking: true

  # If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
  #goatCounter:
  #  code: code

  # If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
  #cloudflare:
  #  token: token

  # If you want to use Matomo(https://matomo.org) for analytics, add this section
  #matomo:
  #  siteID: ABCDE # Default value is 1, overwrite this if you are cloud-hosting
  #  serverURL: analytics.example.com # For cloud-hosting, use provided URL, e.g. example.matomo.cloud

  # If you want to use Google Tag Manager(https://analytics.google.com/) for analytics, add this section
  #googleTagManager:
  #  id: gid

  # If you want to use Yandex Metrika(https://metrika.yandex.ru) for analytics, add this section
  #yandexMetrika:
  #  id: gid

  # If you want to use Application Insights(https://azure.com/) for analytics, add this section
  #applicationInsights:
  #  connectionString: connectionString

  # If you want to use microanalytics.io for analytics, add this section
  #microAnalytics:
  #  id: ABCDE
  #  dnt: false # respect DNT tracker, true by default

  # If you want to use Pirsch(https://pirsch.io) for analytics, add this section
  #pirsch:
  #  code: ABCDE

  # If you want to implement a Content-Security-Policy, add this section
  #csp:
  #  childsrc: [self]
  #  fontsrc: [self, https://fonts.gstatic.com, https://cdn.jsdelivr.net/]
  #  formaction: [self]
  #  framesrc: [self, https://www.youtube.com]
  #  imgsrc: [self]
  #  objectsrc: [none]
  #  stylesrc: [self,unsafe-inline,https://fonts.googleapis.com/,https://cdn.jsdelivr.net/]

  #scriptsrc: [self,unsafe-inline,https://www.google-analytics.com,https://cdn.jsdelivr.net/]

  #prefetchsrc: [self]
  # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
  #connectsrc: [self,https://www.google-analytics.com]

  social:
    - name: github
      icon: fa fa-2x fa-github
      weight: 1
      url: https://github.com/MichaelSchaecher/
    #- name: Gitlab
    #  icon: fa fa-2x fa-gitlab
    #  weight: 2
    #  url: https://gitlab.com/
    #- name: Twitter
    #  icon: fa fa-2x fa-twitter
    #  weight: 3
    #  url: https://twitter.com/
    #- name: LinkedIn
    #  icon: fa fa-2x fa-linkedin
    #  weight: 4
    #  url: https://www.linkedin.com/
    #- name: Medium
    #  icon: fa fa-2x fa-medium
    #  weight: 5
    #  url: https://medium.com/
    #- name: RSS
    #  icon: fa fa-2x fa-rss
    #  weight: 6
    #  url: https://myhugosite.com/
    #  rel: alternate
    #  type: application/rss+xml

taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors

languages:
  en:
    languageName: us

menu:
  main:
    - name: Posts
      weight: 1
      url: /posts/
    - name: Projects
      weight: 2
      url: projects/
    - name: About
      weight: 3
      url: /about/
